auth:
  gofile:
    api_key: null
  jdownloader:
    device_name: null
    email: null
    password: null
  mega_nz:
    email: null
    password: null
  nova:
    api_key: null
  pixeldrain:
    api_key: null
  real_debrid:
    api_key: null
cookies: null
crawlers:
  bandcamp:
    formats:
      - mp3-320
      - mp3
      - aac-hi
      - wav
      - flac
      - vorbis
      - aiff
      - alas
  clonr:
    use_source: false
    zip: false
  clypit:
    prefer_mp3: false
  disabled: []
  generic:
    chevereto: []
    discourse: []
    kvs: []
    peertube: []
    video: []
    wordpress_html: []
    wordpress_media: []
  google_drive:
    default_formats:
      docs: docx
      sheets: xslx
      slides: pptx
  octave_music:
    filename_format: "{artist} - {title}{ext}"
    quality: mp3-320
  one_pace:
    prefer_dub: false
  only_haven:
    attachments: true
    content_urls: true
    embed: true
    file: true
  pawchive:
    attachments: true
    content_urls: true
    embed: true
    file: true
  pornhub:
    profile_paths:
      - photos/public
      - gifs/public
      - videos
      - videos/upload
  tiktok:
    original: false
  twitter:
    articles:
      cover: true
      media: true
    cards: true
    content_urls: true
    image_size: orig
    retweets: false
    threads: true
deep_scrape: false
delete_empty_folders: true
delete_partial_files: false
download_folder: downloads/cyberdrop-dl
downloads:
  attempts: 2
  back_pressure: true
  concurrency: 15
  concurrency_per_domain: 5
  concurrent_segments: 10
  delay: 0.0
  jitter: 0.0
  skip_and_mark_completed: false
  slow_speed: 0B
  speed_limit: 0B
dump_json: false
filters:
  after: null
  allow_files_with_no_extension: false
  before: null
  duration:
    audio:
      max: null
      min: null
    video:
      max: null
      min: null
  filename_regex: null
  filename_regex_exclude: null
  files:
    audio: true
    images: true
    non_media: true
    thumbnails: false
    videos: true
  only_hosts: []
  sizes:
    audio:
      max: null
      min: null
    image:
      max: null
      min: null
    non_media:
      max: null
      min: null
    video:
      max: null
      min: null
  skip_hosts: []
hashing:
  algorithms:
    - xxh128
    - md5
    - sha256
  dedupe:
    enabled: true
    use_trash_bin: true
  mode: in_place
ignore_hashes: false
ignore_history: false
jdownloader:
  autostart: false
  deprecated_api: null
  download_folder: null
  enabled: false
  whitelist: []
logs:
  console_level: null
  expire_after: null
  files:
    download_errors: download_errors.csv
    last_forum_post: last_forum_post.csv
    main: downloader.log
    scrape_errors: scrape_errors.csv
    unsupported: unsupported.csv
  folder: null
  http_traffic: true
  level: DEBUG
  rotate: false
max_children:
  album: 0
  forum: 0
  forum_post: 0
  profile: 0
max_file_name_length: 95
max_folder_name_length: 60
max_thread_depth: 0
max_thread_folder_depth: null
min_free_space: 5.0GiB
mtime: true
network:
  connection_timeout: 15.0
  dump_responses: false
  flaresolverr: null
  flaresolverr_concurrency: 1
  flaresolverr_use_session: true
  flaresolverr_wait: 0
  impersonate: null
  proxy: null
  rate_limit: 25.0
  read_timeout: 300.0
  ssl_context: truststore+certifi
  tls:
    ca_certs: []
    min_version: "1.2"
    verify: true
  user_agent: Mozilla/5.0 (X11; Linux x86_64; rv:153.0) Gecko/20100101 Firefox/153.0
notifications:
  apprise: []
  webhook: null
restrict_path: []
sort:
  enabled: false
  formats:
    audio: "{sort_dir}/{base_dir}/Audio/{filename}{ext}"
    image: "{sort_dir}/{base_dir}/Images/{filename}{ext}"
    incrementer: " ({i})"
    non_media: "{sort_dir}/{base_dir}/Other/{filename}{ext}"
    video: "{sort_dir}/{base_dir}/Videos/{filename}{ext}"
  input_folder: null
  output_folder: downloads/cyberdrop-dl sorted
subfolders:
  create: true
  include:
    album_id: false
    domain: true
    thread_id: false
  separate_posts:
    enabled: false
    format: "{default}"
ui:
  mode: fullscreen
  portrait: false
  refresh_rate: 10.0
  show_stats: true
