body:
  - type: checkboxes
    id: prechecks
    attributes:
      label: I have checked previously requested sites
      description: Before requesting a new site, please review the following cases
      options:
        - label: "The site is not listed in the [wiki's supported sites](https://script-ware.gitbook.io/cyberdrop-dl/reference/supported-websites)"
          required: true
        - label: "I understand this is open source software provided for free and I might not receive a timely response."
          required: true
        - label: "I’ve checked existing issues to avoid creating a duplicate."
          required: true

  - type: input
    id: site-homepage
    attributes:
      label: Site homepage
      placeholder: https://cyberdrop.me
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Describe what kind of content this site provides
      placeholder: |
        1. website that provides comic books and manga
        2. forum which allows its users to share images and videos
        3. specialized in high-res scanned images of physical paintings
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Provide example URLs to support
      description: |
        1. Please include examples of every possible URL you would like to be supported from the site
        2. Add a description of URL format in front of them
        3. The provided URLs must be real and valid

        A few examples:

          Single file: https://<domain>/<file_id>
          Folder / Playlist: https://<domain>/folder/<folder_id>
          Profile: https://<domain>/user/<username>
          Album: https://<domain>/a/<album_id>
          Gallery: https://<domain>/gallery/<gallery_id>

        Also include any edge case you are aware of:

          Password Protected file: https://<domain>/<file_id> (password: <PASSWORD>)
          File (different URL format): https://<domain>/file/<filename>
          Deleted file: https://<domain>/<file_id>

          etc...

    validations:
      required: true

  - type: checkboxes
    id: NSFW
    attributes:
      label: Does this site offer adult content(NSFW)?
      options:
        - label: "This site offers adult content (NSFW)"
          required: false
        - label: "Most of the content on the site is NSFW"
          required: false

  - type: dropdown
    id: mimetype
    attributes:
      label: What kind of content can be found on the site?
      multiple: true
      options:
        - Videos / Gifs
        - Images
        - Audio
        - Others
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Include any additional information that may be relevant to support this site
      placeholder: |
        - Needs an account to download files
        - Blocked in the US
        - Has a known rate limit of 20 requests per second
        - Similar to <other site that cyberdrop-dl already supports>
    id: additional-context

description: Request for a new site to be supported
labels: [ "new website" ]
assignees: [ jbsparrow ]
title: "[SITE SUPPORT] <enter site homepage URL here>"
name: New Site Request
