name: Apprise

on:
  push:
    paths:
      - cyberdrop_dl/utils/apprise.py
    branches:
      - master
  pull_request:
    paths:
      - cyberdrop_dl/utils/apprise.py
    branches:
      - master
  workflow_dispatch:

jobs:
  test_apprise:
    env:
      APPRISE_TEST_EMAIL_URL: ${{ secrets.APPRISE_TEST_EMAIL_URL }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install

      - name: Run pytest
        run: |
          poetry run pytest --cov
