name: CI (using uv)

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'cyberdrop_dl/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'cyberdrop_dl/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

env:
  COLUMNS: 150
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.13, pypy-3.11]
        exclude:
          # sendtotrash and browser_cookies3 need pywin32, which has some cpython specific implementation details
          # https://github.com/mhammond/pywin32/issues/1289
          - os: windows-latest
            python-version: "pypy-3.11"
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv (Python ${{ matrix.python-version }})
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - run: 'uv run python -c "import pydantic.version; print(pydantic.version.version_info())"'

      - name: Run pytest
        timeout-minutes: 10
        run: |
          uv run pytest -v --cov --ignore=tests/test_apprise.py
