name: CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'cyberdrop_dl/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'cyberdrop_dl/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

jobs:
  no-build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          python-version: [3.11, 3.12, 3.13, 3.14 ]
        fail-fast: false

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CDL
        run: uv tool install --no-build cyberdrop-dl-patched


  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11, 3.13, 3.14, pypy-3.11]
        exclude:
          # sendtotrash and browser_cookies3 need pywin32, which has some cpython specific implementation details
          # https://github.com/mhammond/pywin32/issues/1289
          - os: windows-latest
            python-version: "pypy-3.11"
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install

      - name: Run pytest
        timeout-minutes: 10
        run: |
          poetry run pytest -v --cov --ignore=tests/test_apprise.py
