name: CI

on:
  push:
    branches:
      - main
    paths:
      - "cyberdrop_dl/**/*.py"
      - "tests/**/*.py"
      - ".github/workflows/ci.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "cyberdrop_dl/**/*.py"
      - "cyberdrop_dl/pyproject.toml"
      - "tests/**/*.py"
      - ".github/workflows/ci.yaml"
  workflow_dispatch:

permissions: {}

jobs:
  type_check:
    name: Type check
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0
        with:
          enable-cache: false

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras

      - run: uvx basedpyright cyberdrop_dl --level error
        timeout-minutes: 5

  test:
    name: Run pytest
    permissions:
      contents: read

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12, 3.14]
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: false

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras

      - name: Run pytest
        timeout-minutes: 10
        run: |
          uv run pytest --ignore=tests/test_ffmpeg.py -v --cov
