name: FFmpeg

on:
  pull_request:
    branches:
      - main
    paths:
      - "cyberdrop_dl/ffmpeg.py"
      - "cyberdrop_dl/pyproject.toml"
      - "tests/test_ffmpeg.py"
  workflow_dispatch:

permissions: {}

jobs:
  test_ffmpeg:
    name: FFmpeg tests
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: false

      - name: Install dependencies
        run: |
          sudo apt install ffmpeg -y
          uv sync --locked --all-extras

      - name: Run pytest
        timeout-minutes: 10
        run: |
          uv run pytest tests/test_ffmpeg.py -v --cov
